---
- name: pull mini_project image
  hosts: all
  tasks:             
          - name: Pull devops image 
            docker_image:
                  name: sk12092001/calculator
                  source: pull

          - name : Running container
            shell: docker run -it -d sk12092001/calculator /bin/bash
